### ISSUE TITLE
{"error":"unexpected end of JSON input","message":" 视频链接解析失败，请检查视频链接是否正确"}

### ISSUE THREAD

**Issue by goxofy** [disingn/cliptalk#6]
好像不work 了

**Comment by disingn** [comment]
视频链接发一下

**Comment by goxofy** [comment]
就是 readme 里的也不行

**Comment by disingn** [comment]
> 就是 readme 里的也不行

好的 明天我看看怎么回事

**Comment by xyy002** [comment]
> 就是 readme 里的也不行

抖音的接口失效了，现在需要使用一个cookie，暂时的解决办法是：访问web版的douyin，将cookie复制放在api. GetDouYinVideoInfo()这个函数中
大概就是这个样子：req.Header.Add("Cookie",＂cookie＂)

**Comment by disingn** [comment]
> > 就是 readme 里的也不行
> 
> 抖音的接口失效了，现在需要使用一个cookie，暂时的解决办法是：访问web版的douyin，将cookie复制放在api. GetDouYinVideoInfo()这个函数中
> 大概就是这个样子：req.Header.Add("Cookie",＂cookie＂)

是的 这样是可行的 Doyin的接口不会一直作维护

**Comment by goxofy** [comment]
@disingn 现在加上 cookie 也不行了，貌似改了返回的 json 格式

**Comment by disingn** [comment]
> @disingn 现在加上 cookie 也不行了，貌似改了返回的 json 格式

抖音的接口发生了变化，没办法一直维护这个接口，变动太快了
